- name: Get config variable
  get_config:
      vars: bonds

- include_tasks: bond.yml
  when: bonds is not none

# - block:
#     - include_tasks: intent_template.yml
#
#     - name: Intent config
#       set_fact:
#           intent_cfg: "{{ intent_template.splitlines() }}"
#
#     - name: Running config
#       set_fact:
#           running_cfg: "{{ show_config['msg'] | find_cfg('net add bond (?!peerlink).*') }}"
#
#     - name: NCLU del/add commands
#       set_fact:
#           nclu: "{{ running_cfg | bond_nclu(intent_cfg, bonds) }}"
#
#     - name: Delete config
#       nclu:
#           template: |
#               {% for cfg in nclu['del'] %}
#               {{ cfg }}
#               {% endfor %}
#       changed_when: not ansible_check_mode
#       when: nclu['del'] | length > 0
#
#     - name: Add config
#       nclu:
#           template: |
#               {% for cfg in nclu['add'] %}
#               {{ cfg }}
#               {% endfor %}
#       changed_when: not ansible_check_mode
#       when: nclu['add'] | length > 0
#       register: add_bond
#
#     - block:
#         - name: Delete bond conflict
#           nclu:
#               template: |
#                   {% set del_bond = add_bond['msg'] | regex_findall('(?<=enslaved to )\w+') %}
#                   {% for bond in del_bond %}
#                   del bond {{ bond }}
#                   {% endfor %}
#               abort: true
#
#         - name: "{{ 'Commited changes' if not ansible_check_mode else 'Pending changes' }}"
#           nclu:
#               commands:
#               - "{{ 'commit' if not ansible_check_mode else 'pending' }}"
#           register: commit_bond_conflict
#           changed_when: not ansible_check_mode
#           tags: [print_action]
#
#         - name: Fail bond conflict
#           fail:
#               msg: |
#                   {% for er in add_bond['msg'] | regex_findall('interface \\w+ is already enslaved to \\w+') %}
#                   {{ er }}
#                   {% endfor %}
#
#                   The pending changes above must be committed first by
#                   running the command below to avoid error in the later commit.
#                   $ ansible-playbook configs.yml -l {{ inventory_hostname }} -t bond
#           when: ansible_check_mode
#
#         - name: End play
#           meta: end_play
#       when: add_bond['msg'] is defined and (add_bond['msg'] | regex_findall('interface \\w+ is already enslaved to \\w+')) | length > 0
#
#     # - name: End play
#     #   meta: end_play
#     #   when: commit_bond_conflict is defined and commit_bond_conflict is changed
#
#     - name: "{{ 'Commited changes' if not ansible_check_mode else 'Pending changes' }}"
#       nclu:
#           commands:
#           - "{{ 'commit' if not ansible_check_mode else 'pending' }}"
#       when: nclu['del'] | length > 0 or nclu['add'] | length > 0
#       changed_when: not ansible_check_mode
#       tags: [print_action]
#   when: bonds is not none
#   check_mode: false
