- include: check.yml

- name: generate bond vars
  template:
    src: bond.j2
    dest: "{{ hostvars_dir }}/bond.yml"
  delegate_to: localhost
  register: bond_vars
  when: inventory_hostname in groups['leaf']

- name: load host bond vars
  include_vars:
    file: "{{ hostvars_dir }}/bond.yml"
  when: bond_vars is changed

- include: nclu.yml
