- name: net show interface bonds json
  command: net show interface bonds json
  register: net_show_iface_bonds
  changed_when: false

- name: net_show_iface_bonds.stdout
  set_fact:
    iface_bond_cstate: "{{ net_show_iface_bonds.stdout }}"

- name: bond interface intent state
  set_fact:
    iface_bond_istate: "{{ bonding_ | map(attribute='name') | list }}"

- name: delete bond interface not in intent state
  nclu:
    template: |
      {% for item in iface_bond_cstate | dict2items | map(attribute='key') | reject('search', 'peerlink') | list if item not in iface_bond_istate %}
      del bond {{ item }}
      {% endfor %}
    commit: true

- name: configure bond interface
  nclu:
    template: |
      {% for item in bonding_ %}
      add bond {{ item.name }} bond slaves {{ item.slaves }}
      add bond {{ item.name }} alias {{ item.description }}
      add bond {{ item.name }} clag id {{ item.clag_id }}
      {% if item.mode == 'access' %}
      add bond {{ item.name }} bridge access {{ item.vlans | join(',') }}
      {% else %}
      add bond {{ item.name }} bridge trunk vlans {{ item.vlans | join(',') }}
      {% endif %}
      {% endfor %}
    commit: true
  when: bonding_ is iterable
