# compare bonds in variable and running config.
# delete if there is bonds in running config which is not in bond variable

- name: net show clag json
  command: net show clag id json
  register: net_show_clag

- set_fact:
    net_show_clag_: "{{ net_show_clag.stdout }}"

- set_fact:
    switch_bond: |
      {{ net_show_clag_ | dict2items | map(attribute='key') | list }}

- set_fact:
    var_bond: |
      {{ bonding_ | map(attribute='name') | list }}

- set_fact:
    diff_bond: "{{ switch_bond | difference(var_bond)}}"

- nclu:
    template: |
      {% for item in diff_bond %}
      del bond {{ item }}
      {% endfor %}
    commit: true
  when: "diff_bond != '[]'"
