- name: SVI INTENT CONFIGURATION COMMANDS
  set_fact:
      intentconfgs: |
          {%  set _svi = svi[inventory_hostname] %}
          {%  if _svi['l2svi'] | length > 0 %}
          {%      for iface in _svi['l2svi'] %}
          net add vlan {{ iface['vid'] }} vlan-id {{ iface['vid'] }}
          net add vlan {{ iface['vid'] }} vlan-raw-device bridge
          net add vlan {{ iface['vid'] }} ip address {{ iface['ip'] }}
          net add vlan {{ iface['vid'] }} ip address-virtual {{ iface['vhwaddr'] }} {{ iface['vip'] }}
          net add vlan {{ iface['vid'] }} vrf {{ iface['vrf'] }}
          {%      endfor %}
          {%  endif %}
          {%  for iface in _svi['l3svi'] %}
          net add vlan {{ iface['vid'] }} vlan-id {{ iface['vid'] }}
          net add vlan {{ iface['vid'] }} vlan-raw-device bridge
          net add vlan {{ iface['vid'] }} vrf {{ iface['vrf'] }}
          {%      if iface['router_mac'] is defined %}
          net add vlan {{ iface['vid'] }} hwaddress {{ iface['router_mac'] }}
          {%      endif %}
          {% endfor %}
