- name: configure vlan interface for anycast gw
  nclu:
    template: |
      {% for vlan in vlans %}
      {% set virtual_mac = '44:38:39:FF:01:00' | hwaddr('int') + vlan.id %}
      {% set ipaddress = tenants_ | selectattr('vlan_id', 'equalto', vlan.id) | map(attribute='subnet') | join('') %}
      {% set vrf = tenants_ | selectattr('vlan_id', 'equalto', vlan.id) | map(attribute='vrf') | join('') %}
      add vlan {{ vlan.id }} ip address {{ ipaddress | ipaddr(node_id) }}
      add vlan {{ vlan.id }} ip address-virtual {{ virtual_mac | hwaddr('linux') }} {{ ipaddress | ipaddr('-2') }}
      add vlan {{ vlan.id }} vrf {{ vrf }}
      {% endfor %}
    commit: true
  when: vlans is defined and vlans is iterable

- name: configure vlan interface for l3 vni
  nclu:
    template: |
      {% set l3vni = vlans | map(attribute='l3vni') | list | unique %}
      {% for item in l3vni %}
      {% set vrf = tenants_ | selectattr('l3vni', 'equalto', item) | map(attribute='vrf') | list | unique | join('') %}
      {% set router_mac = '44:39:39:FF:FF:FF' | hwaddr('int') - rack_id %}
      add vlan {{ item }} vrf {{ vrf }}
      add vlan {{ item }} hwaddress {{ router_mac | hwaddr('linux') }}
      {% endfor %}
    commit: true
  when: vlans is defined and vlans is iterable

- name: configure vlan interface for l3 vni
  nclu:
    template: |
      {% set l3vni = tenants_ | map(attribute='l3vni') | list | unique %}
      {% for item in l3vni %}
      {% set vrf = tenants_ | selectattr('l3vni', 'equalto', item) | map(attribute='vrf') | list | unique | join('') %}
      add vlan {{ item }} vrf {{ vrf }}
      {% endfor %}
    commit: true
  when: inventory_hostname in groups['border-leaf']
