- name: generate host svi variables
  set_fact:
    svi: "{{ 'svi' | get_config }}"
  run_once: true

- name: net show interface all json
  nclu:
    commands:
      - show interface json
  register: net_show
  changed_when: false

- name: vlan interfaces running configs (1)
  set_fact:
    running_interfaces: "{{ net_show['msg'] }}"

- name: net del vlan interfaces
  nclu:
    template: |
      {%  set vifs =  running_interfaces.keys() | select('search', 'vlan') | reject('search', '-v') | list %}
      {%  for vif in vifs %}
      {%      set _vif = vif.split('vlan')[1] %}
      {%      if _vif not in svi[inventory_hostname].keys() %}
      del vlan {{ _vif }}
      {%      endif %}
      {%  endfor %}
    abort: true
  register: nclu
- name: commit changes (1)
  nclu:
    commands:
      - commit
  when: nclu['changed']

- name: net show configuration commands | egrep 'net add vlan|net add vrf \w+ vni [0-9]'
  shell: "net show configuration commands | egrep 'net add vlan|net add vrf \\w+ vni [0-9]'"
  register: _running_configs
  ignore_errors: true
  changed_when: false

- name: vlan interfaces running configs (2)
  set_fact:
    running_configs: "{{ _running_configs.stdout_lines | map('trim') | list }}"

- name: vlan interfaces intent configs
  set_fact:
    intent_configs: |
      {% for id, svi in svi[inventory_hostname].items() %}
      {%    if svi.type == 'l2' %}
      net add vlan {{ id }} ip address {{ svi.address }}
      net add vlan {{ id }} ip address-virtual {{ svi.virtual_mac }} {{ svi.virtual_address }}
      net add vlan {{ id }} vlan-id {{ id }}
      net add vlan {{ id }} vlan-raw-device bridge
      net add vlan {{ id }} vrf {{ svi.tenant }}
      {%    endif %}
      {%    if svi.type == 'l3' %}
      net add vlan {{ id }} vlan-id {{ id }}
      net add vlan {{ id }} vlan-raw-device bridge
      net add vlan {{ id }} vrf {{ svi.tenant }}
      net add vrf {{ svi['tenant'] }} vni {{ id }}
      {%    endif %}
      {%    if svi.router_mac is defined %}
      net add vlan {{ id }} hwaddress {{ svi.router_mac }}
      {%    endif %}
      {% endfor %}

- name: net del/add vlan interfaces
  nclu:
    template: |
      {%  set nclu = [] %}
      {%  set _intent_configs = intent_configs.split('\n') | reject('equalto', '') | list %}
      {%  for item_del in running_configs if item_del not in _intent_configs %}
      {%      set _item_del = item_del.replace('net add', 'del') %}
      {%      do nclu.append(_item_del) %}{% endfor %}
      {%  for item_add in _intent_configs if item_add not in running_configs %}
      {%      set _item_add = item_add.replace('net add', 'add') %}
      {%      do nclu.append(_item_add) %}{% endfor %}
      {%  for item in nclu %}
      {{ item }}
      {%  endfor %}
    abort: true
  register: nclu
- name: commit changes (2)
  nclu:
    commands:
      - commit
  when: nclu['changed']
