- name: SET SVI VARIABLES
  set_fact:
      svi: "{{ 'vlans_interface' | get_config }}"
  run_once: true

- block:
    - name: RUNNING SWITCH VLAN INTERFACES
      set_fact:
          run_svi_interfaces: "{{ confg_commands['msg']
              | regex_findall('(?<=net add vlan )(\\d+)(?= vlan-id.*)') }}"

    - name: NET DEL SVI INTERFACES
      nclu:
          template: |
              {%  set vids = svi[inventory_hostname]['vids'] %}
              {%  for iface in run_svi_interfaces if iface not in vids %}
              del vlan {{ iface }}
              {%  endfor %}
      register: svi_

    - name: SVI RUNNING CONFIGURATION COMMANDS
      set_fact:
          runconfgs: |
              {%  set vids = svi[inventory_hostname]['vids'] %}
              {%  for iface in run_svi_interfaces if iface not in vids %}
              {%      do run_svi_interfaces.remove(iface) %}
              {%  endfor %}
              {%  set _confg_commands = confg_commands['msg'] |
                      regex_findall('net add vlan.*') %}
              {%  set new_runconfgs = [] %}
              {%  for confg in _confg_commands
                      if confg | regex_search('(?<=vlan )\d+') in run_svi_interfaces %}
              {%      do new_runconfgs.append(confg) %}
              {%  endfor %}
              {{ new_runconfgs }}

    #***** Change 'intent.yml' file for intent configurations commands *****#
    - include_tasks: intent.yml

    - name: PUSH SVI INTENT CONFIGURATION COMMANDS
      nclu:
          template: |
              {%  set _intentconfgs = intentconfgs.split('\n') |
                      reject('equalto', '') | list %}
              {%  for confg in runconfgs if confg not in _intentconfgs %}
              {{ confg.replace('net add', 'del') }}
              {%  endfor %}
              {%  for confg in _intentconfgs if confg not in runconfgs %}
              {{ confg.replace('net add', 'add') }}
              {%  endfor %}
      register: _svi

    - name: "{{ 'COMMITTED CHANGES' if not ansible_check_mode else 'PENDING CHANGES' }}"
      nclu:
          commands:
          - "{{ 'commit' if not ansible_check_mode else 'pending' }}"
      when: svi_ is changed or _svi is changed
      changed_when: not ansible_check_mode
      tags: [print_action]
  when: inventory_hostname in svi
  check_mode: false

#net add vrf {{ iface['vrf'] }} vni {{ iface['vni'] }}
