- include: nclu.yml

#- name: configure vlan interface for anycast gw
#  set_fact:
#    template00: |
#      {% for vlan in vlans %}
#      {% set virtual_mac = '44:38:39:FF:00:05' | hwaddr('int') + loop.index0 %}
#      {% set ipaddress = tenants_ | selectattr('vlan_id', 'equalto', vlan.id) | map(attribute='subnet') | join('') %}
#      {% set vrf = tenants_ | selectattr('vlan_id', 'equalto', vlan.id) | map(attribute='vrf') | join('') %}
#      add vlan {{ vlan.id }} ip address {{ ipaddress | ipaddr(node_id) }}
#      add vlan {{ vlan.id }} ip address-virtual {{ virtual_mac | hwaddr('linux') }} {{ ipaddress | ipaddr('-2') }}
#      vrf {{ vrf }}
#      {% endfor %}
#
#- name: configure vlan interface for l3 vni
#  set_fact:
#    template01: |
#      {% set l3vni = vlans | map(attribute='l3vni') | list | unique %}
#      {% for item in l3vni %}
#      {% set vrf = tenants_ | selectattr('l3vni', 'equalto', item) | map(attribute='vrf') | list | unique | join('') %}
#      {% set router_mac = '44:39:39:FF:FF:FF' | hwaddr('int') - loop.index %}
#      add vlan {{ item }} vrf {{ vrf }}
#      add vlan {{ item }} hwaddress {{ router_mac | hwaddr('linux') }}
#      {% endfor %}
#
#- name: map vrf to l3 vni
#  set_fact:
#    template02: |
#      {% set l3vni = vlans | map(attribute='l3vni') | list | unique %}
#      {% for item in l3vni %}
#      {% set vrf = tenants_ | selectattr('l3vni', 'equalto', item) | map(attribute='vrf') | list | unique | join('') %}
#      add vrf {{ vrf }} vni {{ vxlan_base_id + item }}
#      {% endfor %}
