- name: net show configuration commands | egrep 'net add bond (\w+,.*|\w+) .[^ond].*'
  shell: "net show configuration commands | egrep 'net add bond (\\w+,.*|\\w+) .[^ond].*'"
  register: _running_configs
  ignore_errors: true
  changed_when: false

- name: bonds running configs
  set_fact:
    running_configs: "{{ _running_configs.stdout_lines | map('trim') | list }}"

- name: bonds intent configs
  set_fact:
    intent_configs: |
      {%  set x = [] %}
      {%  set bonds = mlag[inventory_hostname]['bonds'] %}
      {%  for bond, value in bonds.items() %}
      {%      do value.update({'name': bond}) %}
      {%      do x.append(value) %}
      net add bond {{ bond }} clag id {{ value.clag_id }}
      {%  endfor %}
      {%  for k, v in x | groupby('vids') %}
      {%      set _bonds = v | map(attribute='name') | list %}
      {%      if k | cluster_to_range | length > 1 %}
      net add bond {{ _bonds | join(',') }} bridge vids {{ k }}
      {%      else %}
      net add bond {{ _bonds | join(',') }} bridge access {{ k }}
      {%      endif %}
      {%  endfor %}

- name: net del/add bond
  nclu:
    template: |
      {%  set nclu = [] %}
      {%  set _intent_configs = intent_configs.split('\n') | reject('equalto', '') | list %}
      {%  for item_add in _intent_configs if item_add not in running_configs %}
      {%    set _item_add = item_add.replace('net add', 'add') %}
      {%      do nclu.append(_item_add) %}
      {%  endfor %}
      {%  for item in nclu %}
      {{ item }}
      {%  endfor %}
    abort: true
  register: nclu
- name: commit changes (4)
  nclu:
    commands:
      - commit
  when: nclu['changed']
