- name: net show configuration commands | egrep 'net add interface peerlink'
  shell: "net show configuration commands | egrep 'net add interface peerlink'"
  register: _running_configs
  ignore_errors: true
  changed_when: false

- name: peerlink interface running configs
  set_fact:
    running_configs: "{{ _running_configs.stdout_lines }}"

- name: peerlink interface intent configs
  set_fact:
    intent_configs: |
      {% set peer = mlag[inventory_hostname]['peer'] %}
      net add interface peerlink.4094 clag backup-ip {{ peer['backup_ip'] }}
      net add interface peerlink.4094 clag peer-ip {{ peer['peer_ip'] }}
      net add interface peerlink.4094 clag priority {{ peer['priority'] }}
      net add interface peerlink.4094 clag sys-mac {{ peer['system_mac'] }}
      net add interface peerlink.4094 ip address {{ peer['ip'] }}

- name: net del/add bond peerlink interface
  nclu:
    template: |
      {%  set nclu = [] %}
      {%  set _intent_configs = intent_configs.split('\n') | reject('equalto', '') | list %}
      {%  for item_add in _intent_configs if item_add not in running_configs %}
      {%    set _item_add = item_add.replace('net', '').strip() %}
      {%      do nclu.append(_item_add) %}
      {%  endfor %}
      {% for item in nclu %}
      {{ item }}
      {% endfor %}
  register: nclu
- name: commit changes (3)
  nclu:
    commands:
      - commit
  when: nclu['changed']
