# Convenient play to run a add/del/show command
- name: ad-hoc
  hosts: cumulus
  gather_facts: false
  vars_prompt:
    - name: "command"
      prompt: "Enter command"
      private: no
  tasks:
  - command: "{{ command }}"
    register: output

  - debug: msg="{{ output }}"
