- name: NETWORK DEVICE
  hosts: network_device
  gather_facts: false
  roles:
      - { role: setup, tags: always }
      - { role: loopback, tags: [loopback, bgp-evpn, mlag-peerlink, vxlan] }
      - { role: mlag-peerlink, tags: [mlag-peerlink, mlag-bonds, vxlan, svi] }
      - { role: mlag-bonds, tags: [mlag-bonds, vxlan, svi] }
      - { role: vxlan, tags: [vxlan, svi] }
      - { role: svi, tags: svi }
      - { role: ip-interfaces, tags: [ip-interfaces, bgp-evpn] }
      - { role: route-maps, tags: [route-map, bgp-evpn] }
      - { role: bgp-evpn, tags: bgp-evpn }
      - { role: reset, tags: [never, reset] }
      - { role: upgrade, tags: [never, upgrade] }

- name: SERVER
  hosts: server
  gather_facts: false
  roles:
      - { role: server-interfaces, tags: server-interfaces }
