- name: NETWORK_DEVICE
  hosts: network_device
  gather_facts: false
  any_errors_fatal: true
  roles:
    - { role: setup, tags: always }
    - { role: loopback, tags: always }

- name: CUMULUS
  hosts: cumulus
  gather_facts: false
  roles:
    - { role: mlag-peerlink, tags: [mlag-peerlink, mlag-bonds, vxlan, svi] }
    - { role: mlag-bonds, tags: [mlag-bonds, vxlan, svi] }
    - { role: vxlan, tags: [vxlan, svi] }
    - { role: svi, tags: svi }
    - { role: ip-interfaces, tags: [ip-interfaces, bgp-evpn] }
    - { role: route-maps, tags: [route-map, bgp-evpn] }
    - { role: bgp-evpn, tags: bgp-evpn }
    - { role: reset, tags: [never, reset] }
    - { role: upgrade, tags: [never, upgrade] }

- name: EDGE
  hosts: edge
  gather_facts: false
  roles:
    - { role: ip-interfaces, tags: [ip-interfaces, bgp-evpn] }
    - { role: nat, tags: nat }
    - { role: bgp-evpn, tags: bgp-evpn }

- name: SERVER
  hosts: server
  gather_facts: false
  roles:
    - { role: server-interfaces, tags: server-interfaces }
