- name: DNSMASQ
  hosts: localhost
  gather_facts: false
  tasks:

  - include_vars: 'master.yml'
  
  - name: UPDATE DNSMASQ.CONF
    template:
        src: 'dnsmasq.j2'
        dest: '/etc/dnsmasq.conf'
    register: dnsmasq

  - block:
      - name: TEST DNSMASQ CONFIG
        shell: 'dnsmasq --test'

      - name: RESTART DNSMASQ SERVICE
        systemd:
            name: dnsmasq
            state: restarted

      - name: SUCCESS
        debug:
            msg: 'Dnsmasq successfully updated'
        changed_when: true
        tags: [print_action]
    when: dnsmasq is changed
