- name: update dhcp.conf and inventory file
  hosts: localhost
  gather_facts: false
  vars:
    pdir: "{{ playbook_dir | dirname }}"
    ptemplates: "{{ pdir }}/templates"
    pfiles: "{{ pdir }}/files"
    pvars: "{{ pdir }}/vars"
  tasks:

  - name: load variables dhcp
    include_vars:
      dir: "{{ pvars }}"

  - fail: msg="DHCP static host is empty. Check the 'vars/dhcp-host.yml'"
    when: static_host is not sequence

  - name: update inventory
    template:
      src: "{{ ptemplates }}/devices.j2"
      dest: "{{ pdir }}/devices"

  - meta: refresh_inventory

  - name: generate dhcpd.conf file
    template:
      src:  "{{ ptemplates }}/dhcpd.j2"
      dest: "{{ pfiles }}/dhcpd.conf"
    register: dhcpd_conf

  - name: copy dhcp.conf
    copy:
      src: "{{ pfiles }}/dhcpd.conf"
      dest: /etc/dhcp/dhcpd.conf
    when: dhcpd_conf is changed

  - name: restart isc-dhcp-server
    systemd:
      name: "isc-dhcp-server"
      state: restarted
    when: dhcpd_conf is changed
