- name: update dhcp.conf and inventory file
  hosts: localhost
  gather_facts: false
  tasks:
  - name: load variables
    include_vars: "{{ playbook_dir }}/vars/dhcp-host.yml"

  - name: update inventory
    template:
      src: dhcp-inventory.j2
      dest: devices

  - name: generate dhcpd.conf file
    template:
      src: dhcpd.j2
      dest: "{{ playbook_dir }}/templates/dhcpd.conf"
    register: dhcpd_conf

  - name: copy dhcp.conf
    copy:
      src: "{{ playbook_dir }}/templates/dhcpd.conf"
      dest: /etc/dhcp/dhcpd.conf
    when: dhcpd_conf is changed

  - name: restart isc-dhcp-server
    systemd:
      name: "isc-dhcp-server"
      state: restarted
    when: dhcpd_conf is changed

  - meta: refresh_inventory
