- name: netq show
  hosts: spine01
  gather_facts: false
  vars_prompt:
    - name: "netq_host"
      prompt: "Enter hostname"
      private: no
    - name: "netq_show"
      prompt: "netq show"
      private: no
  tasks:
  - command: netq {{ item }} show {{ netq_show }} json
    loop: "{{ netq_host.split(',') }}"
    register: show

  - debug: msg="{{ item.stdout }}"
    loop: "{{ show.results }}"
