# This play is imported by the deploy.yml do not use as a standalone play

- name: PROVISION
  hosts: "{{ hostvars['localhost']['new_hosts'] }}"
  gather_facts: no
  vars:
      ansible_ssh_pass: "{{ default_pass }}"
  pre_tasks:
      - wait_for_connection:
            timeout: 30
        register: _ping
        ignore_errors: true

      - name: REMOVE OLD SSH KEY
        command: "{{ _ping['msg'] | regex_search('ssh-keygen.*') }}"
        delegate_to: localhost
        register: remove_old_ssh_key
        when: _ping is failed and _ping['msg'] is search('ssh-keygen.*')

      - fail:
            msg: |
                device is unreachable (mgmt_hwaddr={{ mgmt_hwaddr }}).
                Make sure the device has the correct mgmt_hwaddr variable in inventory file also check if it was started
        when: _ping is failed and (
          _ping['msg'] is search('No route to host') or
          _ping['msg'] is search('Connection timed out') or
          _ping['msg'] is search('Temporary failure in name resolution')
          )

  roles:
      - role: setup
      - role: loopback
      - role: mlag-peerlink
      - role: mlag-bonds
      - role: vxlan
      - role: svi
      - role: ip-interfaces
      - role: route-maps
      - role: bgp-evpn
      - role: nat
      - role: server-interfaces

  post_tasks:
      - debug: msg="Rebooting"
        tags: [print_action]

      - reboot:

      - name: DEPLOY SSH KEY
        authorized_key:
            user: "{{ ansible_user }}"
            key: "{{ lookup('file', '/home/%s/.ssh/id_rsa.pub' | format(lookup('env', 'USER'))) }}"
            state: present
        register: ssh_key

      - name: ADD MGMT VRF
        nclu:
            commands:
            - add vrf mgmt
            commit: true
        async: 5
        poll: 0
        when: inventory_hostname in groups['cumulus']
        changed_when: false

      - set_fact: deployed="{{ true }}"
