# This play is imported by the deploy.yml do not use as a standalone play

- name: PROVISION
  hosts: "{{ hostvars['localhost']['new_hosts'] }}"
  gather_facts: no
  vars:
      ansible_ssh_pass: "{{ default_pass }}"
  pre_tasks:
      - name: Waiting for connection
        wait_for_connection:
            timeout: 10
        register: _ping
        until: _ping is success
        retries: 10

      - name: Remove old ssh key
        command: "{{ _ping['msg'] | regex_search('ssh-keygen.*') }}"
        delegate_to: localhost
        register: remove_old_ssh_key
        when: _ping is failed and _ping['msg'] is search('ssh-keygen.*')

      - name: Fail
        fail:
            msg: |
                Check if the device is:
                    1. Connected to management network
                    2. Turn on
                    3. Has a correct mgmt_hwaddr({{ mgmt_hwaddr }}) variable in inventory file
        when: _ping is failed and (
          _ping['msg'] is search('No route to host') or
          _ping['msg'] is search('Connection timed out') or
          _ping['msg'] is search('Temporary failure in name resolution')
          )

  roles:
      - role: setup
      - role: loopback
      - role: peerlink
      - role: bond
      - role: vxlan
      - role: svi
      - role: ip-interface
      - role: route-map
      - role: vrf
      - role: bgp
      - role: nat
      - role: server-interface

  post_tasks:
      - debug: msg="Rebooting"
        tags: [print_action]
      - reboot:

      - name: DEPLOY SSH KEY
        authorized_key:
            user: "{{ ansible_user }}"
            key: "{{ lookup('file', '/home/%s/.ssh/id_rsa.pub' | format(lookup('env', 'USER'))) }}"
            state: present
        register: ssh_key

      - name: ADD MGMT VRF
        nclu:
            commands:
            - add vrf mgmt
            commit: true
        async: 5
        poll: 0
        when: inventory_hostname in groups['cumulus']
        changed_when: false

      - set_fact: deployed="{{ true }}"
