- name: reset to default config
  hosts: cumulus
  gather_facts: false
  tasks:

  - name: net del all
    shell: "net del all && net commit"

  - name: reboot switch
    shell: "sleep 5 && reboot"
    async: 5
    poll: 0

  - name: wait for switch to boot up
    wait_for_connection: delay=20

  - name: add mgmt vrf
    shell: "net add vrf mgmt && net commit"
    async: 5
    poll: 0

  - name: reconnect to switch
    wait_for_connection:
