- name: RESET TO DEFAULT CONFIG
  hosts: cumulus
  gather_facts: false
  vars_prompt:
      - name: reset
        prompt: "Delete all configurations? [y/n]"
        default: 'n'
        private: no
  tasks:
  - block:

    - name: DELETING ALL CURRENT CONFIGS
      nclu:
          commands:
              - del all
          commit: true
      register: del_all

    - block:
        - name: REBOOT DEVICE
          shell: "sleep 5 && reboot"
          async: 5
          poll: 0

        - name: WAITING FOR DEVICE TO BOOT UP
          wait_for_connection:
              delay: 10

        - name: RESET SUCCESSFUL
          debug:
              msg: "RESET SUCCESSFUL"
          tags: [print_action]
      when: del_all is changed
    when: reset == 'y'

  - name: DEVICE IS ALREADY AT DEFAULT CONFIG
    debug:
        msg: "DEVICE IS ALREADY AT DEFAULT CONFIG"
    when: del_all is not changed
    tags: [print_action]
