- hosts: dhcp_dns01
  gather_facts: false
  tasks:

  - name: generate dnsmasq.conf
    template:
      src: 'dnsmasq.j2'
      dest: '/etc/dnsmasq.conf'

  - name: test dnsmasq config
    shell: 'dnsmasq --test'

  - name: restart dnsmasq service
    systemd:
      name: dnsmasq
      state: restarted
