- hosts: cumulus
  gather_facts: no
  tasks:

  - name: WAITING FOR CONNECTION
    wait_for_connection:
        timeout: 4
    failed_when: false
    register: _ping

  - name: DEVICE IS UNREACHABLE
    debug: msg="{{ inventory_hostname }} is unreachable. Make sure the device is boot up"
    when: _ping['elapsed'] >= 4
    tags: [print_action]

  - name: WAITING FOR CONNECTION
    wait_for_connection:
    when: _ping['elapsed'] >= 4

  - name: DEPLOY SSH KEY
    authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ lookup('file', '/home/%s/.ssh/id_rsa.pub' | format(lookup('env', 'USER'))) }}"
      state: present

  - name: ADD MGMT VRF
    nclu:
        commands:
        - add vrf mgmt
        commit: true
    async: 5
    poll: 0

  - name: RECONNECTING TO THE DEVICE
    wait_for_connection:
        delay: 5

  - name: DEBUG
    debug:
        msg: |
            *** ssh key file was succesfully loaded ***
            Run the command below if you want to upgrade the device.
            $ ansible-playbook upgrade.yml -l {{ play_hosts | join(',') }}
            Or run the command below to deploy the rest of configurations.
            $ ansible-playbook deploy.yml -l {{ play_hosts | join(',') }}
    tags: [print_action]
    run_once: true
    delegate_to: localhost
