- name: test 000
  hosts: all
  gather_facts: false
  tasks:

  - include_vars:
      dir: vars

  - set_fact:
      var_bond_vids: |
        {% set rack = bonding | dict2items %}
        {% for item in rack if item.key | regex_search('(?<=\d)\d+') | int == rack_id | int %}
        {{ item.value.host_bond | map(attribute='vids') | flatten | unique }}
        {% endfor %}

  - set_fact:
      test00: |
        {% set rack = bonding | dict2items %}
        {% for item in rack if item.key | regex_search('(?<=\d)\d+') | int == rack_id | int %}
        {% for item1 in item.value.host_bond %}
        {% set vrf = tenants_ | selectattr('vlan_name', 'equalto', item1.vids.split(',')[0]) | map(attribute='vrf') | join('') %}
        - name: {{ 'bond' + (loop.index) | string + '-' + vrf }}
          slaves: {{ item1.slaves }}
          clag_id: {{ loop.index }}
          mode: {{ 'access' if item1.vids | wordcount == 1 else 'trunk' }}
          vlans:
        {% for vlan in item1.vids.split(',') %}
            - {{ tenants_ | selectattr('vlan_name', 'equalto', vlan) | map(attribute='vlan_id') | join('') }}
        {% endfor %}
        {% endfor %}
        {% endfor %}

  - debug: msg="{{ test00.split('\n') }}"
