- name: UPGRADE TO LATEST DISTRIBUTION
  hosts: cumulus
  gather_facts: no
  tasks:

  - name: CURRENT VERSION
    nclu:
        commands:
          - show version
    tags: [print_action]

  - name: PING WWW.GOOGLE.COM
    shell: 'ping -c 5 www.google.com -I mgmt'
    register: ping
    failed_when: false
    changed_when: false

  - name: INTERNET IS UNREACHABLE
    fail:
        msg: CANNOT CONNECT TO THE INTERNET
    when: ping.rc == 2 or ping.rc == 1

  - name: UPGRADING DEVICE
    debug:
        msg: "Do not interrupt the upgrade might take a while"
    tags: [print_action]

  - name: UPGRADE DEVICE DISTRIBUTION
    apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
    register: upgrade

  - block:
      - name: REBOOT DEVICE
        shell: "sleep 5 && reboot"
        async: 5
        poll: 0

      - name: WAITING FOR DEVICE TO BOOT UP
        wait_for_connection:
            delay: 10

      - name: UPGRADE SUCCESSFUL
        nclu:
            commands:
              - show version
        tags: [print_action]
    when: upgrade is changed

  - name: DEVICE IS ALREADY UP-TO-DATE
    nclu:
        commands:
          - show version
    tags: [print_action]
