- name: generate host clag variables
  shell: 'python scripts/main.py ip_interface'
  register: var_output
  delegate_to: localhost
  run_once: true
  changed_when: false

- name: set ip_interface variables
  set_fact:
    ip_interface: "{{ var_output['stdout'] }}"
