- name: net show configuration commands | egrep 'net add interface \w+([0-9]|[0-9].\w+) (ip|vrf).* [^m]'
  shell: "net show configuration commands | egrep 'net add interface \\w+([0-9]|[0-9].\\w+) (ip|vrf).* [^m]'"
  register: _running_configs
  ignore_errors: true
  changed_when: false

- name: interfaces ip running configs
  set_fact:
    running_configs: "{{ _running_configs.stdout_lines | map('trim') | list }}"

- name: interfaces ip intent configs
  set_fact:
    intent_configs: |
      {% for vif, value in interfaces_ip[inventory_hostname].items() %}
      net add interface {{ vif }} ip address {{ value['ipv4_address'] }}
      net add interface {{ vif }} vrf {{ value['vrf'] }}
      {% endfor %}

- name: net del/add interfaces ip
  nclu:
    template: |
      abort
      {%  set nclu = [] %}
      {%  set _intent_configs = intent_configs.split('\n') | reject('equalto', '') | list %}
      {%  for item_del in running_configs if item_del not in _intent_configs %}
      {%      set _item_del = item_del.replace('net add', 'del') %}
      {%      do nclu.append(_item_del) %}{% endfor %}
      {%  for item_add in _intent_configs if item_add not in running_configs %}
      {%      set _item_add = item_add.replace('net add', 'add') %}
      {%      do nclu.append(_item_add) %}{% endfor %}
      {%  for item in nclu %}
      {{ item }}
      {%  endfor %}
    abort: true
  register: nclu
- name: commit changes
  nclu:
    commands:
      - commit
  when: nclu['changed']
