- name: generate host clag variables
  shell: 'python scripts/main.py interfaces_ip'
  register: var_output
  delegate_to: localhost
  run_once: true
  changed_when: false

- name: set ip_interface variables
  set_fact:
    interfaces_ip: "{{ var_output['stdout'] }}"
