bonding_:
  - name: bond0
    description: cust1 bond
    slaves: swp1
    clag_id: 1
    mode: trunk
    vlans:
      - 10
      - 11
  - name: bond1
    description: cust2 bond
    slaves: swp2
    clag_id: 2
    mode: trunk
    vlans:
      - 40
      - 41
