- block:
    - name: CHECK IF HOST IS REACHABLE
      wait_for_connection:
          timeout: 10
      register: _ping
      failed_when: false

    - fail:
          msg: |
              {{ _ping['msg'] | regex_search('(?<=22: ).*') }}
              *** Steps to resolve the error ***
              1) For newly added device
                  1.1) Shutdown the device if already boot up
                  1.2) Make sure {{ inventory_hostname }} has the correct mgmt_hwaddr variable in devices file
                  1.3) Run the command 'ansible-playbook dnsmasq.yml' to update the dnsmasq.conf"
                  1.4) Start the device and wait to fully boot up
                  1.5) Run the command 'ansible-playbook ssh-key.yml -l {{ inventory_hostname }} --ask-pass'
                       to load the ssh key file to the device for the first time
              2) If you are sure that the device was working previously just make sure the device is fully boot up
      when: _ping['elapsed'] >= 3 and (
        _ping['msg'] is search('No route to host') or
        _ping['msg'] is search('Connection timed out') or
        _ping['msg'] is search('Temporary failure in name resolution')
        )

    - fail:
          msg: |
              *** Run the command below and provide the device ssh password ***
              *** to load the ssh key file to the device for the first time ***
              'ansible-playbook ssh-key.yml -l {{ inventory_hostname }} --ask-pass'
      when: _ping['elapsed'] >= 3 and _ping['msg'] is search("\\w+@\\w+\:\ Permission denied")

    - name: ABORT ALL PENDING CHANGES
      nclu:
          commands:
            - abort
      changed_when: false

    - name: NET SHOW CONFIGURATION COMMANDS
      nclu:
          commands:
            - show configuration commands
      register: confg_commands
      changed_when: false
  check_mode: false
