- block:
    - name: ABORT ALL PENDING CHANGES
      nclu:
          commands:
            - abort
      changed_when: false

    - name: NET SHOW CONFIGURATION COMMANDS
      nclu:
          commands:
            - show configuration commands
      register: confg_commands
      changed_when: false
  check_mode: false
