- name: generate vlan vars
  template:
    src: vlan.j2
    dest: "{{ hostvars_dir }}/vlan.yml"
  register: vlan_vars
  delegate_to: localhost
  when: bonding_ is defined

- name: load host vlan vars
  include_vars:
    file: "{{ hostvars_dir }}/vlan.yml"
  when: vlan_vars is changed

- include: check.yml

- include: nclu.yml
