- name: Intent config
  set_fact:
      intent: |
          {% for interface, v in vxlan['interfaces'].items() %}
          net add vxlan {{ interface }} vxlan id {{ v['id'] }}
          net add vxlan {{ interface }} bridge access {{ v['vid'] }}
          {%    if v['type'] == 'l2' %}
          net add vxlan {{ interface }} bridge arp-nd-suppress on
          net add vxlan {{ interface }} stp bpduguard
          net add vxlan {{ interface }} stp portbpdufilter
          {%    endif %}
          net add vxlan {{ interface }} vxlan local-tunnelip {{ vxlan['local_tunnelip'] }}
          net add vxlan {{ interface }} bridge learning off
          {% endfor %}

- name: "{{ 'Committed changes ' if not ansible_check_mode else 'Pending changes' }}"
  cml_vxlan:
      running: "{{ show_config['msg'] }}"
      intent: "{{ intent }}"


# - block:
#     - include_tasks: intent_template.yml
#
#     - name: Intent config
#       set_fact:
#           intent_cfg: "{{ intent_template.splitlines() }}"
#
#     - name: Running config
#       set_fact:
#           running_cfg: "{{ show_config['msg'] | find_cfg('net add vxlan.*') }}"
#
#     - name: NCLU del/add commands
#       set_fact:
#           nclu: "{{ 'vxlan' | interface_nclu(running_cfg, intent_cfg, vxlan['interfaces']) }}"
#
#     - name: Delete config
#       nclu:
#           template: |
#               {% for cfg in nclu['del'] %}
#               {{ cfg }}
#               {% endfor %}
#       changed_when: not ansible_check_mode
#       when: nclu['del'] | length > 0
#       register: del_vxlan
#
#     - name: Add config
#       nclu:
#           template: |
#               {% for cfg in nclu['add'] %}
#               {{ cfg }}
#               {% endfor %}
#       changed_when: not ansible_check_mode
#       when: nclu['add'] | length > 0
#       register: add_vxlan
#
#     - name: "{{ 'Commited changes' if not ansible_check_mode else 'Pending changes' }}"
#       nclu:
#           commands:
#           - "{{ 'commit' if not ansible_check_mode else 'pending' }}"
#       when: nclu['del'] | length > 0 or nclu['add'] | length > 0
#       changed_when: not ansible_check_mode
#       tags: [print_action]
#   when: vxlan is not none
#   check_mode: false
