- name: SET SERVER VLANS INTERFACE
  set_fact:
      server_interfaces: "{{ 'server_interfaces' | get_config }}"
  run_once: true

- block:
      - name: MGMT PORT
        set_fact:
            mgmt_port: "{{ server_interfaces[inventory_hostname]['mgmt']['port'] }}"
            mgmt_gateway: "{{ server_interfaces[inventory_hostname]['mgmt']['gateway'] }}"

      - command: cat /etc/network/interfaces
        changed_when: false
        register: temp_iface_config

      - include_tasks: temp-interfaces.yml
        when: (temp_iface_config['stdout'] | regex_findall('(?<=auto )\w+')) | length <= 2

      - name: CHECK IF IFUPDOWN2 IS INSTALLED
        shell: "dpkg -l | grep ifupdown2 | awk '{print $3}'"
        register: ifupdown2

      - include_tasks: ifupdown2.yml
        when: ifupdown2['stdout'] != '1.2.1'

      - include_tasks: interfaces.yml
  when: inventory_hostname in server_interfaces
