- name: TEMP INTERFACES TEMPLATE
  set_fact:
      temp_iface_config: |
          auto lo
          iface lo inet loopback

          auto {{ mgmt_port }}
          iface {{ mgmt_port }} inet dhcp
              # Workaround having multiple gateway, change into VRF in the future
              up /sbin/ip route add default via {{ mgmt_gateway }} metric 100

- name: UPDATE TEMP INTERFACES
  copy:
      content: "{{ temp_iface_config }}"
      dest: /etc/network/interfaces
  diff: true
  register: _temp_iface_config

- name: DHCLIENT EXIT HOOK TEMPLATE
  set_fact:
      dhcp_sethostname: |
          # This script sets the machine hostname to the hostname sent from the DHCP server.
          # If you want to enable this script, change SETHOSTNAME to "yes"
          # Copyright 2013, 2015, 2017, Cumulus Networks, Inc.  All rights reserved.

          SETHOSTNAME="yes"

          if [ $SETHOSTNAME = "yes" ] && [ ! -z $new_host_name ]
          then
              hostname $new_host_name
              sed --in-place -e "/127\.0\.1\.1/s/^.*$/127.0.1.1  $new_host_name/" /etc/hosts
          fi

- name: COPY DHCLIENT EXIT HOOK
  copy:
      content: "{{ dhcp_sethostname }}"
      dest: /etc/dhcp/dhclient-exit-hooks.d/dhcp-sethostname
  register: dhclient

- name: RESTART MGMT INTERFACE
  shell: "ifdown {{ mgmt_port }} && ifup {{ mgmt_port }}"
  when: _temp_iface_config is changed or dhclient is changed
