- block:
    - name: ROUTE-MAP RUNNING CONFIGURATION COMMANDS
      set_fact:
          runconfgs: "{{ confg_commands['msg']
              | regex_findall('net add routing route-map.*') }}"

    - name: ROUTE-MAP RUNNING CONFIGURATION COMMANDS
      set_fact:
          runconfgs: "{{ confg_commands['msg']
              | regex_findall('net add routing route-map.*') }}"

    #***** Change 'intent.yml' file for intent configurations commands *****#
    - include_tasks: intent.yml

    - name: PUSH ROUTE-MAP INTENT CONFIGURATION COMMANDS
      nclu:
          template: |
              {%  set _intentconfgs = intentconfgs.split('\n') |
                      reject('equalto', '') | list %}
              {%  for confg in runconfgs if confg not in _intentconfgs %}
              {{ confg.replace('net add', 'del') | regex_search('del routing route-map \S+ (\w+ \d+)') }}
              {%  endfor %}
              {%  for confg in _intentconfgs if confg not in runconfgs %}
              {{ confg.replace('net add', 'add') }}
              {%  endfor %}
      register: _ip_interfaces

    - name: "{{ 'COMMITTED CHANGES' if not ansible_check_mode else 'PENDING CHANGES' }}"
      nclu:
          commands:
          - "{{ 'commit' if not ansible_check_mode else 'pending' }}"
      when: _ip_interfaces['changed']
      changed_when: not ansible_check_mode
      tags: [print_action]

  check_mode: false
