- name: NAT INTENT CONFIGURATION COMMANDS
  set_fact:
      intentconfgs: |
          {# Default NAT for oob-mgmt network #}
          {%  for item in nat[inventory_hostname] %}
          set nat source rule {{ item['rule'] }} outbound-interface '{{ item['interface'] }}'
          set nat source rule {{ item['rule'] }} source address '{{ item['src_addr'] }}'
          set nat source rule {{ item['rule'] }} translation address 'masquerade'
          set nat source rule {{ item['rule'] }} description '{{ item['name'] }}'
          {%  endfor %}
