- name: Intent config
  set_fact:
      intent: |
          net add routing route-map LOOPBACK_ROUTES permit 10 match interface lo

- name: "{{ 'Committed changes ' if not ansible_check_mode else 'Pending changes' }}"
  cml_route_map:
      running: "{{ show_config['msg'] }}"
      intent: "{{ intent }}"
