- pause:
      prompt: |
          Delete all configurations? [yes/no]
  register: input
  run_once: true

- name: reset
  set_fact:
      response: |
          {%  set res = input['user_input'] | lower %}
          {{ true  if res == 'yes' or res == 'y' else false }}

- include_tasks: "{{ ansible_network_os }}/main.yml"
  when: response
