- name: show configuration commands| egrep 'set interfaces loopback \w+.*'
  vyos_command:
    commands:
        - show configuration commands| egrep 'set interfaces loopback \w+.*'
  register: show

- name: loopback running configs
  set_fact:
    running_configs: "{{ show.stdout_lines | flatten | reject('equalto', '') | list  }}"

- name: loopback intent configs
  set_fact:
    intent_configs: |
      {%  for ip in loopback[inventory_hostname]['ip_addresses'] %}
      set interfaces loopback lo address '{{ ip }}'
      {%  endfor %}

- name: loopback commands
  set_fact:
    commands: |
      {%  set vyos = [] %}
      {%  set _intent_configs = intent_configs.split('\n') | reject('equalto', '') | list %}
      {%  for item_del in running_configs if item_del not in _intent_configs %}
      {%      set _item_del = item_del.replace('set', 'delete').strip() %}
      {%      do vyos.append(_item_del) %}{% endfor %}
      {%  for item_add in _intent_configs if item_add not in running_configs %}
      {%      set _item_add = item_add.strip() %}
      {%      do vyos.append(_item_add) %}{% endfor %}
      {{ vyos }}

- name: set/delete loopback configs
  vyos_config:
    lines:
      - "{{ item }}"
    save: yes
  loop: "{{ commands }}"
  when: commands | length > 0
