- name: Fail host is unreachable
  fail:
      msg: |
          {{ _ping['msg'] | regex_search('(?<=22: ).*') }}
          *** Steps to resolve the error ***
          1) For newly added device
                - Make sure the device has the correct mgmt_hwaddr variable in inventory file
                  and run the command 'ansible-playbook deploy.yml'
          2) If you are sure that the device was working previously just make sure it was started
