- name: Wait for connection
  wait_for_connection:
      timeout: 5
  register: _ping

- include_tasks: fail.yml
  when: _ping is failed and (
    _ping['msg'] is search('No route to host') or
    _ping['msg'] is search('Connection timed out') or
    _ping['msg'] is search('Temporary failure in name resolution')
    )

- include_tasks: "{{ ansible_network_os }}/main.yml"
  when: inventory_hostname not in groups['server']
