# - name: load global variables
#   include_vars:
#     file: 'master.yml'

# - name: generate host common variables
#   shell: 'python scripts/main.py common'
#   register: var_output
#   delegate_to: localhost
#   run_once: true
#   changed_when: false
#
# - name: set common variables
#   set_fact:
#     common: "{{ var_output['stdout'] }}"
