- include: check.yml
  when: inventory_hostname in groups['cumulus']
- include: nclu.yml
  when: inventory_hostname in groups['cumulus']
- include: vyos.yml
  when: inventory_hostname in groups['edge-router']
