- name: update dhcp.conf and inventory file
  hosts: localhost
  gather_facts: false
  tasks:

  - name: load variables dhcp
    include_vars: "{{ playbook_vars }}/dhcp-host.yml"

  - fail: msg="DHCP static host is empty. Check the 'vars/dhcp-host.yml'"
    when: static_host is not sequence

  - name: update inventory
    template:
      src: devices.j2
      dest: devices

  - meta: refresh_inventory

  - name: generate dhcpd.conf file
    template:
      src: dhcpd.j2
      dest: files/dhcpd.conf
    register: dhcpd_conf

  - name: copy dhcp.conf
    copy:
      src: files/dhcpd.conf
      dest: /etc/dhcp/dhcpd.conf
    when: dhcpd_conf is changed

  - name: restart isc-dhcp-server
    systemd:
      name: "isc-dhcp-server"
      state: restarted
    when: dhcpd_conf is changed
