- name: netq valid show command
  hosts: localhost
  gather_facts: false
  vars:
    netq_show_list:
      - 'agents      :  Netq agent'
      - 'bgp         :  BGP info'
      - 'clag        :  Cumulus Multi-chassis LAG'
      - 'evpn        :  EVPN'
      - 'interfaces  :  network interface port'
      - 'inventory   :  Inventory information'
      - 'services    :  System services'
      - 'vlan        :  VLAN'
      - 'vxlan       :  VXLAN data path'
  tasks:
  - debug: var=netq_show_list
  
- name: netq show
  hosts: spine01
  gather_facts: false
  vars_prompt:
    - name: "netq_host"
      prompt: "Enter hostname"
      private: no
    - name: "netq_show"
      prompt: "netq show"
      private: no
  tasks:

  - command: netq {{ item }} show {{ netq_show }} json
    loop: "{{ netq_host.split(',') }}"
    register: show

  - debug: msg="{{ item.stdout }}"
    loop: "{{ show.results }}"
